version: '3.8'

services:
  # PostgreSQL Database for development
  postgres:
    image: postgres:15
    container_name: mcp-dev-postgres-1
    environment:
      POSTGRES_DB: mcp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mcp_dev_network

  # Redis Cache for development
  redis:
    image: redis:7-alpine
    container_name: mcp-dev-redis-1
    ports:
      - "6380:6379"
    volumes:
      - dev_redis_data:/data
    networks:
      - mcp_dev_network

  # PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mcp-dev-pgadmin-1
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - dev_pgadmin_data:/var/lib/pgadmin
    networks:
      - mcp_dev_network
    depends_on:
      - postgres

volumes:
  dev_postgres_data:
  dev_redis_data:
  dev_pgadmin_data:

networks:
  mcp_dev_network:
    driver: bridge 