services:
  # Unified development container with all tools
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file: .env
    working_dir: /app
    volumes:
      # Mount application code for live development
      - .:/app
    # Keep container running for development
    tty: true
    stdin_open: true
    # Auto-restart on file changes (default behavior)
    # Override with: docker-compose run dev bash (for interactive shell)
    
  # MCP Server with auto-restart for development
  mcp-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file: .env
    environment:
      - MCP_TRANSPORT=${MCP_TRANSPORT:-stdio}
      - MCP_HOST=${MCP_HOST:-127.0.0.1}
      - MCP_PORT=${MCP_PORT:-3000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    working_dir: /app
    volumes:
      # Mount application code for live development
      - .:/app
    # Auto-restart MCP server on file changes (uses default CMD from Dockerfile)
    # For stdio MCP testing
    stdin_open: true
    # Port mapping for HTTP transport
    ports:
      - "3000:3000"


networks:
  default:
    name: mcp_network 